### ISSUE TITLE
change first lines Dockerfile for compatibility with latest hass.io

### ISSUE THREAD

**Issue by kdw2060** [quentinchap/hassio-repo#1]
Hi,

building this example project fails on Hass.io 0.60 with host-os 1.1 because of the new requirements for Dockerfiles. The first two lines should read:
```
ARG BUILD_FROM
FROM $BUILD_FROM
```
After that it builds without issues.

btw, i found your project because i'm having trouble getting my own simple node based project to work as an add-on. Can I contact you for help if i keep failing to get it to work?

cheers,
Kris

**Comment by quentinchap** [comment]
Hi, 

Thank you for your remarq. I made update for tv-custom-api but i forgot hassio-addon-example. 
If you have some trouble contact me i'll try to help you.

Have a nice day.

**Comment by kdw2060** [comment]
Thanks for the offer, in the mean time i've solved my issues getting the addon to work in Hass.io.
Now debugging other issues :-)
